import blueHoody from "../src/assets/blueHoody.png";

export const FlatCategories = [
    {
        id: 1,
        name: "Men",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["Sports", "Casual","formal","shityshityshit","not shity", "this is shit"],
        description:"Category for men clothing. Acting as a gender."
    },
    {
        id: 2,
        name: "Sports",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["shoes", "fits"],
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
        id: 3,
        name: "Women",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["Sports", "Casual","formal"],
        description:"Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    },
    {
        id: 6,
        name: "Kids",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["Sports", "Casual","formal"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 389,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 397,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 379,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 87,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 76,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 65,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 436,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 546,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 43,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 363,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 36,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 35,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    },
    {
        id: 34,
        name: "Men Formal",
        image:blueHoody,
        parent_id: null,
        total_sales:4553,
        total_products:4343,
        children: ["golden", "grey","black"],
        description:" Duis dignissim diam sit amet libero ultricies, ac molestie nulla vestibulum. Vestibulum tempor, purus ut venenatis elementum,",
    }
]

